
const ITEMS_DB = [
  { id: "T4_MEAL_STEW", es: "Estofado de Cabra (T4)" },
  { id: "T6_MEAL_STEW", es: "Estofado de Ganso (T6)" },
  { id: "T8_MEAL_STEW", es: "Estofado de Ternera (T8)" },
  { id: "T4_MEAL_PIE", es: "Pastel de Cabra (T4)" },
  { id: "T6_MEAL_PIE", es: "Pastel de Ganso (T6)" },
  { id: "T8_MEAL_PIE", es: "Pastel de Ternera (T8)" },
  { id: "T4_MEAL_OMELETTE", es: "Tortilla de Gallina (T4)" },
  { id: "T6_MEAL_OMELETTE", es: "Tortilla de Ganso (T6)" },
  { id: "T8_MEAL_OMELETTE", es: "Tortilla de Cerdo (T8)" },
  { id: "T4_POTION_HEAL", es: "Poción de Curación (T4)" },
  { id: "T6_POTION_HEAL", es: "Poción de Curación Mayor (T6)" },
  { id: "T8_POTION_HEAL", es: "Poción de Curación Magistral (T8)" },
  { id: "T4_POTION_COOLDOWN", es: "Poción de Veneno (T4)" },
  { id: "T6_POTION_COOLDOWN", es: "Poción de Veneno Mayor (T6)" },
  { id: "T8_POTION_COOLDOWN", es: "Poción de Veneno Magistral (T8)" },
  { id: "T4_POTION_INVIS", es: "Poción de Invisibilidad (T4)" },
  { id: "T6_POTION_INVIS", es: "Poción de Invisibilidad Mayor (T6)" },
  { id: "T8_POTION_INVIS", es: "Poción de Invisibilidad Magistral (T8)" },
  { id: "T3_MOUNT_HORSE", es: "Caballo de Montar T3" },
  { id: "T4_MOUNT_HORSE", es: "Caballo de Montar T4" },
  { id: "T5_MOUNT_HORSE", es: "Caballo de Montar T5" },
  { id: "T6_MOUNT_HORSE", es: "Caballo de Montar T6" },
  { id: "T7_MOUNT_HORSE", es: "Caballo de Montar T7" },
  { id: "T8_MOUNT_HORSE", es: "Caballo de Montar T8" },
  { id: "T3_MOUNT_OX", es: "Buey de Transporte T3" },
  { id: "T4_MOUNT_OX", es: "Buey de Transporte T4" },
  { id: "T5_MOUNT_OX", es: "Buey de Transporte T5" },
  { id: "T6_MOUNT_OX", es: "Buey de Transporte T6" },
  { id: "T7_MOUNT_OX", es: "Buey de Transporte T7" },
  { id: "T8_MOUNT_OX", es: "Buey de Transporte T8" },
  { id: "T6_MOUNT_DIREWOLF", es: "Lobo Huargo T6" },
  { id: "MAIN_SWORD", es: "Espada Ancha" }, { id: "2H_CLAYMORE", es: "Claymore" }, { id: "MAIN_SCIMITAR", es: "Espadas Dobles" }, { id: "2H_CLEAVER_HELL", es: "Sangradora" }, { id: "2H_DUALSWORD", es: "Espadas Dobles" },
  { id: "MAIN_AXE", es: "Hacha de Batalla" }, { id: "2H_HALBERD", es: "Alabarda" }, { id: "2H_AXE", es: "Gran Hacha" }, { id: "2H_SCYTHE_HELL", es: "Guadaña Infernal" }, { id: "2H_DUALAXE_KEEPER", es: "Patas de Oso" },
  { id: "MAIN_MACE", es: "Maza" }, { id: "2H_MACE", es: "Maza Pesada" }, { id: "2H_FLAIL", es: "Mangual" }, { id: "MAIN_ROCKMACE_KEEPER", es: "Maza de Íncubo" },
  { id: "MAIN_HAMMER", es: "Martillo" }, { id: "2H_POLEHAMMER", es: "Martillo de Guerra" }, { id: "2H_HAMMER", es: "Gran Martillo" },
  { id: "MAIN_1HSPEAR", es: "Lanza" }, { id: "2H_SPEAR", es: "Pica" }, { id: "2H_GLAIVE", es: "Guja" },
  { id: "MAIN_DAGGER", es: "Daga" }, { id: "2H_DAGGERPAIR", es: "Dagas Dobles" }, { id: "2H_CLAWPAIR", es: "Garras" }, { id: "MAIN_RAPIER_MORGANA", es: "Daga Sangrienta" },
  { id: "2H_BOW", es: "Arco" }, { id: "2H_WARBOW", es: "Arco de Guerra" }, { id: "2H_LONGBOW", es: "Arco Largo" }, { id: "2H_BOW_KEEPER", es: "Arco de Badon" },
  { id: "2H_CROSSBOW", es: "Ballesta" }, { id: "2H_CROSSBOWLARGE", es: "Ballesta Pesada" }, { id: "MAIN_1HCROSSBOW", es: "Ballesta Ligera" },
  { id: "MAIN_FIRESTAFF", es: "Bastón de Fuego" }, { id: "2H_FIRESTAFF", es: "Gran Bastón de Fuego" },
  { id: "MAIN_NATURESTAFF", es: "Bastón de Naturaleza" }, { id: "2H_NATURESTAFF", es: "Gran Bastón de Naturaleza" },
  { id: "MAIN_HOLYSTAFF", es: "Bastón Sagrado" }, { id: "2H_HOLYSTAFF", es: "Gran Bastón Sagrado" },
  { id: "MAIN_CURSEDSTAFF", es: "Bastón Maldito" }, { id: "2H_CURSEDSTAFF", es: "Gran Bastón Maldito" },
  { id: "MAIN_FROSTSTAFF", es: "Bastón de Hielo" }, { id: "2H_FROSTSTAFF", es: "Gran Bastón de Hielo" },
  { id: "MAIN_ARCANESTAFF", es: "Bastón Arcano" }, { id: "2H_ARCANESTAFF", es: "Gran Bastón Arcano" },
  { id: "ARMOR_CLOTH_SET1", es: "Toga de Erudito" }, { id: "HEAD_CLOTH_SET1", es: "Hábito de Erudito" }, { id: "SHOES_CLOTH_SET1", es: "Sandalias de Erudito" },
  { id: "ARMOR_CLOTH_SET2", es: "Toga de Clérigo" }, { id: "HEAD_CLOTH_SET2", es: "Hábito de Clérigo" }, { id: "SHOES_CLOTH_SET2", es: "Sandalias de Clérigo" },
  { id: "ARMOR_CLOTH_SET3", es: "Toga de Mago" }, { id: "HEAD_CLOTH_SET3", es: "Hábito de Mago" }, { id: "SHOES_CLOTH_SET3", es: "Sandalias de Mago" },
  { id: "ARMOR_LEATHER_SET1", es: "Chaqueta de Mercenario" }, { id: "HEAD_LEATHER_SET1", es: "Capucha de Mercenario" }, { id: "SHOES_LEATHER_SET1", es: "Zapatos de Mercenario" },
  { id: "ARMOR_LEATHER_SET2", es: "Chaqueta de Cazador" }, { id: "HEAD_LEATHER_SET2", es: "Capucha de Cazador" }, { id: "SHOES_LEATHER_SET2", es: "Zapatos de Cazador" },
  { id: "ARMOR_LEATHER_SET3", es: "Chaqueta de Asesino" }, { id: "HEAD_LEATHER_SET3", es: "Capucha de Asesino" }, { id: "SHOES_LEATHER_SET3", es: "Zapatos de Asesino" },
  { id: "ARMOR_PLATE_SET1", es: "Armadura de Soldado" }, { id: "HEAD_PLATE_SET1", es: "Casco de Soldado" }, { id: "SHOES_PLATE_SET1", es: "Botas de Soldado" },
  { id: "ARMOR_PLATE_SET2", es: "Armadura de Caballero" }, { id: "HEAD_PLATE_SET2", es: "Casco de Caballero" }, { id: "SHOES_PLATE_SET2", es: "Botas de Caballero" },
  { id: "ARMOR_PLATE_SET3", es: "Armadura de Guardián" }, { id: "HEAD_PLATE_SET3", es: "Casco de Guardián" }, { id: "SHOES_PLATE_SET3", es: "Botas de Guardián" },
  { id: "BAG", es: "Bolsa" }, { id: "CAPE", es: "Capa Normal" }, { id: "CAPEITEM_FW_MARTLOCK", es: "Capa de Martlock" }, { id: "CAPEITEM_FW_THETFORD", es: "Capa de Thetford" }, { id: "CAPEITEM_FW_FORTSTERLING", es: "Capa de Fort Sterling" }, { id: "CAPEITEM_FW_LYMHURST", es: "Capa de Lymhurst" }, { id: "CAPEITEM_FW_BRIDGEWATCH", es: "Capa de Bridgewatch" },
  { id: "CLOTH", es: "Tela" }, { id: "LEATHER", es: "Cuero" }, { id: "METALBAR", es: "Lingote de Metal" }, { id: "PLANKS", es: "Tablas de Madera" }, { id: "STONEBLOCK", es: "Bloque de Piedra" },
  { id: "CARROT", es: "Zanahoria" }, { id: "FARM_CARROT_SEED", es: "Semilla de Zanahoria" },
  { id: "BEAN", es: "Frijoles" }, { id: "FARM_BEAN_SEED", es: "Semilla de Frijoles" },
  { id: "CABBAGE", es: "Repollo" }, { id: "FARM_CABBAGE_SEED", es: "Semilla de Repollo" },
  { id: "POTATO", es: "Patata" }, { id: "FARM_POTATO_SEED", es: "Semilla de Patata" },
  { id: "CORN", es: "Maíz" }, { id: "FARM_CORN_SEED", es: "Semilla de Maíz" },
  { id: "PUMPKIN", es: "Calabaza" }, { id: "FARM_PUMPKIN_SEED", es: "Semilla de Calabaza" },
  { id: "AGARIC", es: "Arcano Agaric (Hierba)" }, { id: "COMFREY", es: "Consuelda (Hierba)" },
  { id: "BURDOCK", es: "Bardana (Hierba)" }, { id: "DRAGONTEASEL", es: "Cardencha (Hierba)" },
  { id: "ELUSIVEFOXGLOVE", es: "Digitalis (Hierba)" }, { id: "FIREBLOOM", es: "Flor de Fuego (Hierba)" },
  { id: "MEAT", es: "Carne Cruda" }, { id: "MILK", es: "Leche" }, { id: "EGG", es: "Huevo" },
  { id: "FARM_HORSE_GROWN", es: "Caballo Criado (Montura Base)" },
  { id: "FARM_OX_GROWN", es: "Buey Criado (Montura Base)" },
  { id: "FARM_DIREWOLF_GROWN", es: "Lobo Huargo Criado (Montura Base)" }
];

const MAPS_DB = [
  { name: "Lymhurst", type: "Ciudad Real", tier: "T3+", pvp: "Segura (Azul)", res: "Madera, Piedra, Piel" },
  { name: "Fort Sterling", type: "Ciudad Real", tier: "T3+", pvp: "Segura (Azul)", res: "Mineral, Piedra, Fibra" },
  { name: "Thetford", type: "Ciudad Real", tier: "T3+", pvp: "Segura (Azul)", res: "Madera, Mineral, Fibra" },
  { name: "Martlock", type: "Ciudad Real", tier: "T3+", pvp: "Segura (Azul)", res: "Madera, Piedra, Mineral" },
  { name: "Bridgewatch", type: "Ciudad Real", tier: "T3+", pvp: "Segura (Azul)", res: "Piel, Piedra, Fibra" },
  { name: "Caerleon", type: "Ciudad (Centro)", tier: "T3+", pvp: "Segura (Azul)", res: "Rodeada de Zonas Rojas" },
  { name: "Brecilien", type: "Ciudad Mística", tier: "T3+", pvp: "Segura (Azul)", res: "Acceso a Nieblas y Caminos" },
  { name: "Eldon Hill", type: "Continente Real", tier: "T5", pvp: "Facción (Amarilla)", res: "Madera, Piedra, Piel" },
  { name: "Roast Oasis", type: "Continente Real", tier: "T6", pvp: "PVP Total (Roja)", res: "Madera, Piedra, Piel" },
  { name: "Arthur's Rest", type: "Zona Negra (Santuario)", tier: "T7", pvp: "Segura", res: "Ninguno" },
  { name: "Sunfang Approach", type: "Zona Negra", tier: "T8", pvp: "PVP Total (Negra)", res: "Piel, Mineral, Fibra" },
  { name: "Caminos Avalonianos", type: "Caminos Avalonianos", tier: "T4-T8", pvp: "PVP Total (Negra)", res: "Todos los recursos aleatorios" }
];
